version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
      - docker build -f Dockerfile.dind . -t littlekbt/docker
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - docker run --rm --privileged -v /usr/local/bin/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock littlekbt/docker sh -c 'sudo docker-compose build && sudo docker-compose run web bundle exec rails db:create && sudo docker-compose run web bundle exec rails test'
  post_build:
    commands:
      - echo Build completed on `date`
