version: 0.2

env:
  variables:
    UNAME: `uname -r`
phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
      - apt-get update
      - apt-get install apt-transport-https ca-certificates
      - apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
      - echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | tee /etc/apt/sources.list.d/docker.list
      - apt-get update
      - echo $UNAME
      - apt-get install linux-image-extra-$UNAME linux-image-extra-virtual
      - apt-get install docker-engine
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - docker run hello-world
  post_build:
    commands:
      - echo Build completed on `date`
