version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
      - curl -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - docker-compose run web bundle exec rails test 
  post_build:
    commands:
      - echo Build completed on `date`
